"""Initial, transactional PostgreSQL import of a consistent local SQLite snapshot.

This is not a runtime adapter or a continuous/bidirectional synchronization tool.
"""

import hashlib
import json
import re
import sqlite3
from pathlib import Path

SCHEMA = "trendradar"
META_TABLE = "_sqlite_import"


def identifier(name):
    if not re.fullmatch(r"[a-z_][a-z_0-9]*", name):
        raise ValueError("unsupported_sql_identifier")
    return '"' + name + '"'


def content_hash(rows):
    """Compare row multisets independently of SQLite/Postgres collation order."""
    hashes = []
    for row in rows:
        values = [
            {"bytes": bytes(v).hex()} if isinstance(v, (bytes, memoryview)) else v
            for v in row
        ]
        raw = json.dumps(values, ensure_ascii=False, allow_nan=False,
                         separators=(",", ":")).encode()
        hashes.append(hashlib.sha256(raw).digest())
    return hashlib.sha256(b"".join(sorted(hashes))).hexdigest()


def postgres_ddl(statement):
    # Only transform SQL tokens, never text inside CHECK/default string literals.
    parts = re.split(r"('(?:''|[^'])*')", statement)
    for i in range(0, len(parts), 2):
        part = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\b",
                      "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", parts[i], flags=re.I)
        for old, new in (("INTEGER", "BIGINT"), ("REAL", "DOUBLE PRECISION"), ("BLOB", "BYTEA")):
            part = re.sub(r"\b" + old + r"\b", new, part, flags=re.I)
        parts[i] = part
    return "".join(parts)


def inspect_snapshot(path):
    db = sqlite3.connect(Path(path).resolve().as_uri() + "?mode=ro", uri=True)
    try:
        db.execute("BEGIN")
        if db.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
            raise ValueError("sqlite_integrity_check_failed")
        if db.execute("PRAGMA foreign_key_check").fetchall():
            raise ValueError("sqlite_foreign_key_check_failed")
        if db.execute("SELECT 1 FROM sqlite_master WHERE type IN ('view','trigger') LIMIT 1").fetchone():
            raise ValueError("sqlite_views_or_triggers_require_manual_migration")
        tables = {}
        for name, ddl in db.execute(
            "SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall():
            quoted = identifier(name)
            if name == META_TABLE:
                raise ValueError("reserved_import_table_name")
            columns = db.execute("PRAGMA table_info(" + quoted + ")").fetchall()
            if any(c[2].upper() not in ("TEXT", "INTEGER", "REAL", "BLOB") for c in columns):
                raise ValueError("unsupported_sqlite_column_type")
            for c in columns:
                identifier(c[1])
            primary = [c[1] for c in sorted(columns, key=lambda c: c[5]) if c[5]]
            if not primary:
                raise ValueError("table_without_primary_key")
            if db.execute("SELECT 1 FROM " + quoted + " WHERE " + " OR ".join(
                identifier(c) + " IS NULL" for c in primary
            ) + " LIMIT 1").fetchone():
                raise ValueError("null_primary_key")
            rows = db.execute("SELECT * FROM " + quoted).fetchall()
            tables[name] = {
                "columns": [c[1] for c in columns], "rows": len(rows),
                "sha256": content_hash(rows), "ddl": postgres_ddl(ddl),
                "dependencies": sorted({r[2] for r in db.execute("PRAGMA foreign_key_list(" + quoted + ")")}),
                "identity": primary[0] if re.search(r"\bINTEGER\s+PRIMARY\s+KEY\b", ddl, re.I) else None,
            }
        order = []
        pending = set(tables)
        while pending:
            ready = sorted(n for n in pending if set(tables[n]["dependencies"]).issubset(order))
            if not ready:
                raise ValueError("cyclic_or_missing_foreign_key_dependency")
            order.extend(ready)
            pending.difference_update(ready)
        indexes = [postgres_ddl(r[0]) for r in db.execute(
            "SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"
        )]
        manifest = {"tables": tables, "order": order, "indexes": indexes}
        manifest["fingerprint"] = hashlib.sha256(json.dumps(
            manifest, sort_keys=True, separators=(",", ":")
        ).encode()).hexdigest()
        return manifest
    finally:
        db.close()


def verify_tables(connection, manifest):
    for name in manifest["order"]:
        table = manifest["tables"][name]
        columns = ",".join(identifier(c) for c in table["columns"])
        rows = connection.execute(
            "SELECT " + columns + " FROM " + identifier(SCHEMA) + "." + identifier(name)
        ).fetchall()
        if len(rows) != table["rows"] or content_hash(rows) != table["sha256"]:
            raise ValueError("remote_content_mismatch:" + name)


def import_snapshot(connection, snapshot, manifest, *, commit=False):
    """Caller supplies an idle autocommit connection; dry validation rolls back."""
    if not connection.autocommit:
        raise ValueError("import_requires_autocommit_connection")
    with connection.transaction(force_rollback=not commit):
        connection.execute("SELECT pg_advisory_xact_lock(734901264182)")
        connection.execute("SET LOCAL statement_timeout='120s'")
        # Supabase may default to 0, rounding float8 text results and breaking
        # exact snapshot hashes even though COPY preserved the stored bits.
        connection.execute("SET LOCAL extra_float_digits=3")
        existing = connection.execute(
            "SELECT 1 FROM pg_namespace WHERE nspname=%s", (SCHEMA,)
        ).fetchone()
        if existing:
            tables = {r[0] for r in connection.execute(
                "SELECT tablename FROM pg_tables WHERE schemaname=%s", (SCHEMA,)
            )}
            if tables != set(manifest["tables"]) | {META_TABLE}:
                raise ValueError("target_schema_already_exists_no_overwrite")
            previous = connection.execute(
                'SELECT fingerprint FROM "trendradar"."_sqlite_import"'
            ).fetchall()
            if previous != [(manifest["fingerprint"],)]:
                raise ValueError("target_snapshot_differs_no_overwrite")
            verify_tables(connection, manifest)
            return "already_imported"
        connection.execute('CREATE SCHEMA "trendradar"')
        connection.execute('REVOKE ALL ON SCHEMA "trendradar" FROM PUBLIC, anon, authenticated')
        connection.execute('SET LOCAL search_path = "trendradar", pg_catalog')
        for name in manifest["order"]:
            connection.execute(manifest["tables"][name]["ddl"])
            # This backend schema must never grant anonymous access to content,
            # email addresses or delivery receipts, including through Data API.
            connection.execute("ALTER TABLE " + identifier(name) + " ENABLE ROW LEVEL SECURITY")
            connection.execute("REVOKE ALL ON TABLE " + identifier(name) + " FROM PUBLIC, anon, authenticated")
        db = sqlite3.connect(Path(snapshot).resolve().as_uri() + "?mode=ro", uri=True)
        try:
            db.execute("BEGIN")
            for name in manifest["order"]:
                table = manifest["tables"][name]
                columns = ",".join(identifier(c) for c in table["columns"])
                with connection.cursor() as cursor:
                    with cursor.copy("COPY " + identifier(name) + " (" + columns + ") FROM STDIN") as copy:
                        for row in db.execute("SELECT " + columns + " FROM " + identifier(name)):
                            copy.write_row(row)
                if table["identity"]:
                    column = identifier(table["identity"])
                    maximum = db.execute("SELECT max(" + column + ") FROM " + identifier(name)).fetchone()[0]
                    connection.execute(
                        "SELECT setval(pg_get_serial_sequence(%s,%s),%s,%s)",
                        (SCHEMA + "." + name, table["identity"], max(1, maximum or 1), maximum is not None),
                    )
        finally:
            db.close()
        for ddl in manifest["indexes"]:
            connection.execute(ddl)
        verify_tables(connection, manifest)
        connection.execute('CREATE TABLE "_sqlite_import" (fingerprint TEXT PRIMARY KEY, imported_at TIMESTAMPTZ NOT NULL DEFAULT now())')
        connection.execute('ALTER TABLE "_sqlite_import" ENABLE ROW LEVEL SECURITY')
        connection.execute('REVOKE ALL ON TABLE "_sqlite_import" FROM PUBLIC, anon, authenticated')
        connection.execute('REVOKE ALL ON ALL SEQUENCES IN SCHEMA "trendradar" FROM PUBLIC, anon, authenticated')
        connection.execute('INSERT INTO "_sqlite_import" (fingerprint) VALUES (%s)', (manifest["fingerprint"],))
    return "imported" if commit else "validated_rolled_back"
