import sqlite3
import tempfile
import unittest
from pathlib import Path

from trendradar.content_pool.store import Store
from trendradar.content_pool.supabase_sync import content_hash, inspect_snapshot, postgres_ddl


class SupabasePlanTests(unittest.TestCase):
    def test_hash_preserves_values_blobs_duplicates_but_not_collation_order(self):
        rows = [(1, "中文", b"\x00\xff", None, 1.25), (2, "", b"", None, 0.0)]
        self.assertEqual(content_hash(rows), content_hash(list(reversed(rows))))
        self.assertEqual(content_hash(rows), content_hash([
            (1, "中文", memoryview(b"\x00\xff"), None, 1.25), rows[1]
        ]))
        self.assertNotEqual(content_hash(rows), content_hash(rows + [rows[0]]))
        self.assertNotEqual(content_hash([(None,)]), content_hash([("",)]))

    def test_sql_preserves_checks_foreign_keys_defaults_and_literal_text(self):
        ddl = "CREATE TABLE t (id INTEGER PRIMARY KEY, data BLOB, cost REAL, n INTEGER DEFAULT 0, label TEXT DEFAULT 'INTEGER BLOB', CHECK(n>=0), FOREIGN KEY(n) REFERENCES parent(id))"
        converted = postgres_ddl(ddl)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", converted)
        self.assertIn("data BYTEA", converted)
        self.assertIn("cost DOUBLE PRECISION", converted)
        self.assertIn("DEFAULT 'INTEGER BLOB'", converted)
        self.assertIn("FOREIGN KEY(n) REFERENCES parent(id)", converted)

    def test_application_schema_foreign_keys_order_and_snapshot_is_read_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "test.sqlite3"
            store = Store(path)
            store.close()
            before = path.read_bytes()
            plan = inspect_snapshot(path)
            self.assertEqual(before, path.read_bytes())
            self.assertIn("papers", plan["tables"])
            self.assertIn("judgments", plan["tables"])
            self.assertEqual(plan["tables"]["fetch_runs"]["identity"], "id")
            for name, table in plan["tables"].items():
                for dependency in table["dependencies"]:
                    self.assertLess(plan["order"].index(dependency), plan["order"].index(name))
            self.assertEqual(inspect_snapshot(path)["fingerprint"], plan["fingerprint"])

    def test_sqlite_nullable_primary_key_is_rejected_before_remote_writes(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "invalid.sqlite3"
            db = sqlite3.connect(path)
            db.execute("CREATE TABLE test (id TEXT PRIMARY KEY)")
            db.execute("INSERT INTO test VALUES (NULL)")
            db.commit()
            db.close()
            with self.assertRaisesRegex(ValueError, "null_primary_key"):
                inspect_snapshot(path)
